feat(table): refactor table component for conditional rendering
kyndryl-design-system/shidoka-applications pull request #137
Opened 2024-03-28 12:34 UTC by peterpham-kyndryl

## Summary

Brief summary describing the changes here.

## ADO Story or GitHub Issue Link

Link here (if applicable).

## Notes

- Detailed change notes
- can go here

## To Do

- Anything else
- left to do

## Checklist

- [ ] Used Conventional Commit messages as outlined in the contributing guide.
  - [ ] Noted breaking changes (if any).
- [ ] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [ ] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [ ] Added/updated a basic unit test, at least, for each component.
- [ ] Added/updated the Figma link for the Story's Design tab.
- [ ] Added any new component exports to the src/index.ts file

## Testing Instructions

Provide guidance to reviewers/testers here.

## Screenshots

(if any)

2024-03-28 17:48 UTC, brian-patrick-3 requested changes
This is looking pretty great, thanks for all your hard work!

Here's a few things I think we still need:

1. Try to restore the deleted components and stories, and avoid any breaking changes if possible as we discussed after the demo. This is what I'm most worried about.
2. Add a Story that shows the table with Pagination. People will be looking for that.
3. The example code is hard to find with the Storybook changes. I would suggest adding links to the sample code/component file on GitHub somewhere in the Docs.
4. We'll also need a Story in the Global Filter that shows it working with a Table. Can maybe follow up on that after this release.

2024-03-28 17:48 UTC, brian-patrick-3 commented on package.json
> +    "@lit/context": "^1.1.0",
This is neat, I didn't even know it was a thing. Could be very useful for component > sub-component communication.

2024-04-01 13:36 UTC, peterpham-kyndryl commented
> This is looking pretty great, thanks for all your hard work!
> 
> Issues I see:
> 
> 1. Selectable version - row checkboxes are not aligned with header checkbox.
> 
> Here's a few things I think we still need:
> 
> 1. Try to restore the deleted components and stories, and avoid any breaking changes if possible as we discussed after the demo. This is what I'm most worried about.
>    
>    1. If breaking changes are unavoidable:
>       
>       1. Make sure your [commit messages call out each breaking change](https://www.conventionalcommits.org/en/v1.0.0/#summary).
>       2. Point this PR to `beta` branch, as we'll have to start a 2.0 release.
> 2. Add a Story that shows the table with Pagination. People will be looking for that.
> 3. The example code is hard to find with the Storybook changes. I would suggest adding links to the sample code/component file on GitHub somewhere in the Docs.
> 4. We'll also need a Story in the Global Filter that shows it working with a Table. Can maybe follow up on that after this release.

@brian-patrick-3 
Thank you!
Regarding the checkboxes issue - I wasn't aware of it since it only happened on FireFox but it's fixed now. I tested on all browsers (chrome, safari on Mac, chrome, firefox and edge), and it's currently working fine on all of them.

Regarding things that we still need:
1. Breaking changes: I double-checked and there's no breaking change. They can keep using the deprecated data table and old basic table. Old stories are now restored with just a tiny change.
2. Pagination stories added to the new table.
3. Link added. Later I can provide my demos in React, Svelte (and probably Angular) so it's easier for them to follow.
4. Sure thing!

2024-04-01 13:57 UTC, brian-patrick-3 approved these changes

2024-04-01 13:58 UTC, merged