fix(RadioCheckbox): alignment fix
kyndryl-design-system/shidoka-applications pull request #255
Opened 2024-10-14 12:52 UTC by kumarivijeta

## Summary

Radio and checkbox input and lable alignment fix

## ADO Story or GitHub Issue Link

Link here (if applicable).

## Notes

- Detailed change notes
- can go here

## Checklist

- [x] Used Conventional Commit messages as outlined in the contributing guide.
  - [ ] Noted breaking changes (if any).
- [ ] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [x] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [ ] Ran `test` locally to address any failures.
- [ ] Added/updated the Figma link for the Story's Design tab.
- [ ] Added any new component exports to the src/index.ts file

2024-10-14 15:25 UTC, brian-patrick-3 requested changes
Let's clean it up a little bit further with `gap: 10px` on the labels, and `margin: 0` on the input/span, then we can merge

2024-10-15 06:59 UTC, jaideep08 approved these changes

2024-10-15 13:40 UTC, brian-patrick-3 approved these changes

2024-10-15 15:08 UTC, srpriyankashetty approved these changes
Verified and I do not see much difference on UI end in Storybook.

2024-10-15 15:11 UTC, merged

2024-10-15 15:17 UTC, brian-patrick-3 commented
:tada: This PR is included in version 1.42.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/shidoka-applications/v/1.42.2)
- [GitHub release](https://github.com/kyndryl-design-system/shidoka-applications/releases/tag/v1.42.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: