feat(formComponent)!: label slot updated to text string and error icon aligned with error message
kyndryl-design-system/shidoka-applications pull request #259
Opened 2024-10-15 14:58 UTC by kumarivijeta

## Summary

Brief summary describing the changes here.

## ADO Story or GitHub Issue Link

Link here (if applicable).

## Notes

- Detailed change notes
- can go here

## To Do

- Anything else
- left to do

## Checklist

- [ ] Used Conventional Commit messages as outlined in the contributing guide.
  - [ ] Noted breaking changes (if any).
- [ ] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [ ] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [ ] Ran `test` locally to address any failures.
- [ ] Added/updated the Figma link for the Story's Design tab.
- [ ] Added any new component exports to the src/index.ts file

## Testing Instructions

Provide guidance to reviewers/testers here.

## Screenshots

(if any)

2024-10-16 14:52 UTC, brian-patrick-3 requested changes

2024-10-16 14:52 UTC, brian-patrick-3 commented on src/stories/migration.mdx
> +    - `errorIcon` has been repositioned outside of the input field and is now displayed inline with the error message
No need to call this out in the migration guide since it's an internal-only change.

2024-10-16 14:52 UTC, brian-patrick-3 commented on src/components/reusable/textInput/textInput.ts
> +  /** Lable text. */
Typo?

2024-10-16 14:56 UTC, kumarivijeta commented on src/components/reusable/textInput/textInput.ts
> +  /** Lable text. */
Updated.

2024-10-16 14:57 UTC, brian-patrick-3 approved these changes

2024-10-17 13:55 UTC, merged

2025-02-12 19:36 UTC, brian-patrick-3 commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/shidoka-applications/v/2.0.0)
- [GitHub release](https://github.com/kyndryl-design-system/shidoka-applications/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: