feat(formComponent)!: label slot to prop update & new tooltip slot
kyndryl-design-system/shidoka-applications pull request #263
Opened 2024-10-17 05:57 UTC by jaideep08

## Summary

Brief summary describing the changes here.

## ADO Story or GitHub Issue Link

Link here (if applicable).

## Figma Link

Link here (if applicable).

## Notes

- Detailed change notes
- can go here

## To Do

- Anything else
- left to do

## Checklist

- [ ] Used Conventional Commit messages as outlined in the contributing guide.
  - [ ] Noted breaking changes (if any).
- [ ] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [ ] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [ ] Ran `test` locally to address any failures.
- [ ] Added/updated the Figma link for the Story's Design tab.
- [ ] Added any new component exports to the src/index.ts file

## Testing Instructions

Provide guidance to reviewers/testers here.

## Screenshots

(if any)

2024-10-17 13:56 UTC, brian-patrick-3 requested changes
I don't see any error icon changes.

2024-10-17 13:56 UTC, brian-patrick-3 commented on src/components/reusable/checkbox/checkboxGroup.ts
> +            <span>${ifDefined(this.label)}</span>
You don't need to use `ifDefined` here, label is required.

2024-10-17 13:56 UTC, brian-patrick-3 commented on src/components/reusable/toggleButton/toggleButton.ts
> + * @slot unnamed - Slot for tooltip.
Name the slot "tooltip" to be consistent with all the other form components.

2024-10-17 13:56 UTC, brian-patrick-3 commented on src/stories/migration.mdx
> +    - `unnamed` slot is for tooltip
Pull in the latest from main containing Vijeta's changes, and add your notes under the section she created.

2024-10-17 15:30 UTC, jaideep08 commented
The error icon was already present for checkbox group and dropdown.

2024-10-17 15:37 UTC, brian-patrick-3 approved these changes

2024-10-18 07:05 UTC, srpriyankashetty commented
Single searchable is not showing the error message when made mandatory

2024-10-18 11:26 UTC, jaideep08 commented
> Single searchable is not showing the error message when made mandatory

Fixed it for both single searchable and multi-select searchable

2024-10-18 11:28 UTC, kumarivijeta approved these changes

2024-10-18 11:39 UTC, kumarivijeta reviewed
The info icon looks larger compared to the label text. Please set the info icon size to 16 to get proper alignment.

2024-10-21 10:55 UTC, srpriyankashetty reviewed
Verified the Checkbox, Dropdown and Toggle button - info icon and the tried changing the label name - looks fine.

2024-10-21 19:00 UTC, merged

2024-10-21 19:05 UTC, brian-patrick-3 commented
:tada: This PR is included in version 2.0.0-next.9 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/shidoka-applications/v/2.0.0-next.9)
- [GitHub release](https://github.com/kyndryl-design-system/shidoka-applications/releases/tag/v2.0.0-next.9)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-02-12 19:36 UTC, brian-patrick-3 commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/shidoka-applications/v/2.0.0)
- [GitHub release](https://github.com/kyndryl-design-system/shidoka-applications/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: