Feat/dropdown
kyndryl-design-system/shidoka-applications pull request #264
Opened 2024-10-17 06:12 UTC by kumarivijeta

## Summary

Brief summary describing the changes here.

## ADO Story or GitHub Issue Link

Link here (if applicable).

## Figma Link

Link here (if applicable).

## Notes

- Detailed change notes
- can go here

## To Do

- Anything else
- left to do

## Checklist

- [ ] Used Conventional Commit messages as outlined in the contributing guide.
  - [ ] Noted breaking changes (if any).
- [ ] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [ ] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [ ] Ran `test` locally to address any failures.
- [ ] Added/updated the Figma link for the Story's Design tab.
- [ ] Added any new component exports to the src/index.ts file

## Testing Instructions

Provide guidance to reviewers/testers here.

## Screenshots

(if any)

2024-10-18 14:01 UTC, brian-patrick-3 commented
Oh I thought of one more important thing. We should make the `selected` prop on dropdown-option private/internal. Maybe rename it to `_selected` also.

2024-10-21 19:05 UTC, brian-patrick-3 requested changes

2024-10-21 19:05 UTC, brian-patrick-3 commented on src/components/reusable/dropdown/dropdown.stories.js
> +        value=""
`value` should be a control/arg in each of these stories

2024-10-21 19:05 UTC, brian-patrick-3 commented on src/components/reusable/dropdown/dropdown.stories.js
> -        ?updateByValue=${args.updateByValue}
This is still pending.

2024-10-22 13:54 UTC, brian-patrick-3 approved these changes
LGTM! Once QA approves, you can squash merge and add the `BREAKING CHANGE:` footer notes.

2024-10-23 08:27 UTC, srpriyankashetty approved these changes
Verified Single, Single searchable, Multiple searchable, Multi select, Grouped and Data driven Option dropdown, by adding the value and looks fine.

![image](https://github.com/user-attachments/assets/8ffbde71-30cd-44f2-90fc-0d8f7949680b)

2024-10-23 10:27 UTC, merged

2024-10-23 10:32 UTC, brian-patrick-3 commented
:tada: This PR is included in version 2.0.0-next.11 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/shidoka-applications/v/2.0.0-next.11)
- [GitHub release](https://github.com/kyndryl-design-system/shidoka-applications/releases/tag/v2.0.0-next.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-02-12 19:36 UTC, brian-patrick-3 commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/shidoka-applications/v/2.0.0)
- [GitHub release](https://github.com/kyndryl-design-system/shidoka-applications/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: