feat(tag): colour token updates
kyndryl-design-system/shidoka-applications pull request #310
Opened 2024-12-20 02:18 UTC by jaideep08

## Summary

Brief summary describing the changes here.

## ADO Story or GitHub Issue Link

Link here (if applicable).

## Figma Link

Link here (if applicable).

## Notes

- Detailed change notes
- can go here

## To Do

- Anything else
- left to do

## Checklist

- [ ] Used Conventional Commit messages as outlined in the contributing guide.
  - [ ] Noted breaking changes (if any).
- [ ] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [ ] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [ ] Ran `test` locally to address any failures.
- [ ] Added/updated the Figma link for the Story's Design tab.
- [ ] Added any new component exports to the src/index.ts file

## Testing Instructions

Provide guidance to reviewers/testers here.

## Screenshots

(if any)

2025-01-07 05:46 UTC, kumarivijeta requested changes
1. Show all/show Less color is not matching with Figma
2. Can we remove shade props? I don't think it is required anymore.

2025-01-07 10:37 UTC, kumarivijeta approved these changes

2025-01-09 10:11 UTC, srpriyankashetty approved these changes
Verified the Tag colors in dark mode
Verified the Tag group in dark mode
Verified the Clickable Tags
Verified Disable Tag color and looks fine

@jaideep08 , observed that close button boarder is bit thicker than Figma.! you can proceed if it's fine from backend.

2025-01-09 10:52 UTC, jaideep08 commented
> Verified the Tag colors in dark mode Verified the Tag group in dark mode Verified the Clickable Tags Verified Disable Tag color and looks fine
> 
> @jaideep08 , observed that close button boarder is bit thicker than Figma.! you can proceed if it's fine from backend.

@srpriyankashetty, fixed it.

2025-01-09 10:57 UTC, merged

2025-01-09 11:00 UTC, brian-patrick-3 commented
:tada: This PR is included in version 2.0.0-next.40 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/shidoka-applications/v/2.0.0-next.40)
- [GitHub release](https://github.com/kyndryl-design-system/shidoka-applications/releases/tag/v2.0.0-next.40)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-02-12 19:35 UTC, brian-patrick-3 commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/shidoka-applications/v/2.0.0)
- [GitHub release](https://github.com/kyndryl-design-system/shidoka-applications/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: